### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by akaduwel1** [FlamingoJournal/cse110-sp21-group18#10]
Add items to and read from storage and display a list of items. 
Storage: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#storing_simple_data_%E2%80%94_web_storage

**Comment by mmjiang-ucsd** [comment]
LocalStorage seems to have limit of 5MB, may need to look into IndexedDB 
https://stackoverflow.com/questions/43563681/store-huge-data-in-localstorage
