### ISSUE TITLE
Calendar Widget

### ISSUE THREAD

**Issue by akaduwel1** [FlamingoJournal/cse110-sp21-group18#7]
Create a demo using one of the calendar elements linked on the miro whiteboard (https://miro.com/app/board/o9J_lJNJRJw=/?moveToWidget=3074457358287525123&cot=14) as well as displaying the date chosen on the calendar.

**Comment by mmjiang-ucsd** [comment]
Method of opening calendar without having to click on the icon (i.e. when you click anywhere else on the input). May have some issues
https://stackoverflow.com/questions/15530850/method-to-show-native-datepicker-in-chrome/45461709#45461709

**Comment by Tekunalogy** [comment]
> Method of opening calendar without having to click on the icon (i.e. when you click anywhere else on the input). May have some issues
> https://stackoverflow.com/questions/15530850/method-to-show-native-datepicker-in-chrome/45461709#45461709

Yes this is perfect. I have implemented this and made some tweaks.
